var Name = "Ejaz";
var name2 = "Ejaz";
var a = 10;
var arr = ["Abc", "xyz"];
console.log(Name === "Ejaz" ? "True" : "False");
console.log(name2 === "Ali" ? "True" : "False");
console.log(Name.toLowerCase() === "ejaz" ? "True" : "False");
console.log(a == 10 ? "True" : "False");
console.log(a != 10 ? "True" : "False");
console.log(a <= 11 ? "True" : "False");
console.log(a >= 8 ? "True" : "False");
console.log(Name && name2 ? "True" : "False");
console.log(Name || name2 ? "True" : "False");
//const b = arr.includes("Ejaz");
//console.log(b);
